### ISSUE TITLE
add tutanota

### ISSUE THREAD

**Issue by elijh** [OpenTechFund/secure-email#25]
https://tutanota.com is one of those systems that does not use openpgp, but allows encrypted messages to other tutanota users. if sending to outside users, then you need to communicate a password to them out of band and they need to click on a link in the email they receive.

it is a web app that is GPLv3 https://github.com/tutao/tutanota

**Comment by pierreozoux** [comment]
:+1:

**Comment by lazzarello** [comment]
Is there a federation model similar to that implemented in email?

**Comment by elijh** [comment]
tutanota is among a long list of things that looks like awesome client encrypted email in the browser but really is not. I say this because they are punting on the central hard problem, which is discovering and validating public openpgp keys. 

effectively, tutanota client is trusting the tutanota server to validate the keys of other tutanota users. for everyone else, there is no public key cryptography, the recipient must have received an out of band shared secret. 

to make a long story short, this is not a federated model.

projects like tutanota and protonmail look just whiteout to the average user, but they are totally different universes. whiteout is the real deal, actual openpgp encrypted webmail (personally, i don't trust the browser, but if you wanted to, the whiteout design is the way you should do it).

**Comment by pierreozoux** [comment]
nice comment @elijh I think the same, but it's a bit better than gmail...

**Comment by dkg** [comment]
I did a quick review of tutanota back in february, which i'm re-posting here:

I have done no code review; i couldn't find a high-level technical or
protocol spec (though i didn't look hard).  I just signed up for a test
account with their service at https://app.tutanota.de, so this review is
based on concerns raised by my interaction with the tool and what i can
infer from that, not on any deeper analysis.

The usual webapp problems
=========================

The web application has the same security problem as any web application
attempting to provide secure/confidential messaging: the web server can
be modified to ship bogus javascript to your browser, and you have to
type your password into the login form, which is controlled by that
javascript.

This leaves room for anyone capable of coercing the site operator into
stealing your password and thereby decrypting all your messages.

I haven't tested the local app versions.  if those are more secure in
some way, they should make it very clear to users that the webapp
interface provides inferior security.

Is this really using asymmetric crypto?
=======================================

The site also claims to use RSA, but if they're using RSA, then they're
doing something odd, because i can (with multiple browsers and browser
profiles) access the same account using only the initial password.

Perhaps they're doing something like what multilock does, where they
derive an RSA key from your password?  in that case, they really should
not allow passwords like "the quick brown fox" (i tried; they do).

Also, if they were doing this, then changing passwords seems like it
should invalidate all the messages that are encrypted on the server
side.  But after i change my password, i can still read all the previous
messages sent.  So this smells a little fishy (i suppose it's possible
that they're re-encrypting all my stored messages when i change my
password; the message store on my test account is not large; i don't
know how well that approach would scale if i were using the full 1GB of
storage they offer).

If they're doing asymmetric crypto but storing the secret keys on their
server (protected only by my passphrase?) that's a bit troubling,
particularly with the webapp password-stealing attack mentioned above.

Key Discovery
============

They appear to have the same key discovery issue that centralized
systems have.  Even if they were to avoid the webapp code distribution
issue somehow, apparently the only way that you can communicate with
other tutanota users is that tutatnota implicitly figures out the keys
for those users.  So this lets the site operator do a key substitution
attack if they want, causing your message to be encrypted to the wrong
keys (or maybe to both the right and wrong keys, so that the legitimate
recipient can read it as well as whoever is requesting the tap).

Messaging to people not on the same server
==========================================

their off-site messaging presents privacy concerns (not to mention
workflow problems) for external users, who only receive a message with a
link back to the tutanota.de server, which they then can open and
decrypt using a shared password that the original sender decided on.
The privacy implication is that the message recipient now has to "phone
home" to the tutanota server to actually read the message. SMTP, for all
its warts, doesn't allow this kind of surveillance by the sender about
who has accessed the message.

When the original sender (from tutanota) sends the same remote account
another e-mail, that e-mail also uses the same shared password as the
first one.  This suggests that the e-mail account for the original
sender needs to retain that shared password in some form accessible to
them at least for sending future messages (it appears to be stored in
the user's addressbook).

Federation unclear
==================

How does this federate?  If i wanted to run my own tutanota instance and
use it to send mail to someone with an @tutanota.de address, how would i
do that sensibly?  surely i don't want to have to keep logging into the
tutanota.de server just to read their replies to me.

Feedback not reachable over tor
===============================

When i click the "feedback" button on their webapp, i get pointed to:

  https://tutanota.uservoice.com/forums/237921-general

which doesn't appear to work over Tor (it's blocked behind the
cloudflare captcha, i think)
